INSERT INTO countries (code, name, dial_code, default_currency, enabled) VALUES
  ('UG', 'Uganda', '256', 'UGX', TRUE),
  ('KE', 'Kenya', '254', 'KES', FALSE),
  ('TZ', 'Tanzania', '255', 'TZS', FALSE),
  ('RW', 'Rwanda', '250', 'RWF', FALSE),
  ('ZM', 'Zambia', '260', 'ZMW', FALSE),
  ('MW', 'Malawi', '265', 'MWK', FALSE),
  ('GH', 'Ghana', '233', 'GHS', FALSE),
  ('CM', 'Cameroon', '237', 'XAF', FALSE),
  ('CI', 'Cote d''Ivoire', '225', 'XOF', FALSE),
  ('BJ', 'Benin', '229', 'XOF', FALSE),
  ('CG', 'Congo Brazzaville', '242', 'XAF', FALSE),
  ('SZ', 'Eswatini', '268', 'SZL', FALSE),
  ('GN', 'Guinea', '224', 'GNF', FALSE),
  ('LR', 'Liberia', '231', 'LRD', FALSE),
  ('SS', 'South Sudan', '211', 'SSP', FALSE),
  ('ZA', 'South Africa', '27', 'ZAR', FALSE),
  ('NG', 'Nigeria', '234', 'NGN', FALSE),
  ('CD', 'DRC', '243', 'CDF', FALSE),
  ('GA', 'Gabon', '241', 'XAF', FALSE),
  ('TD', 'Chad', '235', 'XAF', FALSE),
  ('NE', 'Niger', '227', 'XOF', FALSE),
  ('MG', 'Madagascar', '261', 'MGA', FALSE),
  ('SC', 'Seychelles', '248', 'SCR', FALSE)
ON CONFLICT (code) DO NOTHING;
